### ISSUE TITLE
[Bug] date picker aren't working in CP using Safari

### ISSUE THREAD

**Issue by jimblue** [jrc9designstudio/statamic-google-analytics-v2#14]
Hello,

I would like to report a bug in the control panel.

In the Google Analytics menu the date picker on the top right isn't working.
I've also try in sub-menus (browsers/location/pages views/referrals/settings) but it's not working either.

![screencapture](https://user-images.githubusercontent.com/10623367/64200234-5ba82400-ce8c-11e9-9c28-0cf85202253f.gif)

BTW I'm using Statamic Google Analytics v2.4.0.

Cheers.

**Comment by jcohlmeyer** [comment]
What browser are you using?

**Comment by jimblue** [comment]
@jcohlmeyer sorry I forgot to mention it's happening on Safari, not on Chrome.

**Comment by jcohlmeyer** [comment]
It seems like Safari does not support the date input ☹️ https://caniuse.com/#search=date I will see if I there is anything I can do about this.

I was thinking of changing this option anyway to give a few quick select options like last week, last month, last quarter, last year with an advanced option to select dates.

In the mean time you can type in the dates as 2019-09-09 for example.

**Comment by jimblue** [comment]
Hey!
Quick select option sound the best option IMO, you should get rid of those select date input and make think simpler.
For more advanced analytics it's always possible to visite google analytics website.
