### ISSUE TITLE
Tag for Most Visited

### ISSUE THREAD

**Issue by luizboaretto** [jrc9designstudio/statamic-google-analytics-v2#18]
The widget already exists, but it would be great to have a tag. 😄 

```
{{ google_analytics:most_visited limit=5 period... exclude_home... }}
(...) Top 5 most visited.
{{ /google_analytics:most_visited }}
```

**Comment by jcohlmeyer** [comment]
You can already do most of this for collections using the sorting filter as documented here: https://statamic.com/marketplace/addons/google-analytics/docs#page-hits-sorting-filter

Does this suit your needs, if not could you explain what you are looking for in more detail?

**Comment by luizboaretto** [comment]
@jcohlmeyer this filter seems to work. Thanks! 😃

**Comment by jcohlmeyer** [comment]
Also thanks to your idea I added a period option to this page hits filter and tag here: https://statamic.com/marketplace/addons/google-analytics/changelog

Also you may want to take a look at the page pre-cache command if you have large collections https://statamic.com/marketplace/addons/google-analytics/docs#page-hits-precache
