### ISSUE TITLE
Page views and visitors are reversed in the chart

### ISSUE THREAD

**Issue by than** [jrc9designstudio/statamic-google-analytics-v2#2]
![](https://than.d.pr/lZfmV5.png)

Confirmed that the data is correct, but the page views and visitors values are swapped.

**Comment by jcohlmeyer** [comment]
Thanks for reporting this :)

It is fixed in [2.2.3](https://github.com/jrc9designstudio/statamic-google-analytics-v2/releases/tag/2.2.3)
