### ISSUE TITLE
No data shown

### ISSUE THREAD

**Issue by codybuell** [jrc9designstudio/statamic-google-analytics-v2#5]
Running Statamic 2.10.7 and version 2.2.3 of this plugin.  Settings all appear to be correct, credentials file properly set in Statamic and via Google developer console / analytics, but no data ever shows up on the charts.  The only error on the browser console is:

```javascript
chart.js?v=2.2.3:10 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at i.generateLabels (chart.js?v=2.2.3:10)
    at Object.callback (chart.js?v=2.2.3:10)
    at i.buildLabels (chart.js?v=2.2.3:10)
    at i.update (chart.js?v=2.2.3:10)
    at chart.js?v=2.2.3:10
    at Object.each (chart.js?v=2.2.3:10)
    at Object.update (chart.js?v=2.2.3:10)
    at t.updateLayout (chart.js?v=2.2.3:10)
    at t.update (chart.js?v=2.2.3:10)
    at GoogleAnalyticsDoughnutChart.labels (scripts.js? [sm]:83)
```

Nothing is showing up in the server logs to point to any problems.

**Comment by jcohlmeyer** [comment]
Did you give access to the email from the credentials file to the property in Google Analytics?

**Comment by codybuell** [comment]
I did, Read & Analyze.  Is anything conditional on the environment being local or production?

**Comment by jcohlmeyer** [comment]
This is the only way to do different settings per environment: https://statamic.com/marketplace/addons/google-analytics/docs#environment-support

Other than this nothing depends on the environment.

**Comment by codybuell** [comment]
Any logging done with the plugin? Any suggestions for where to start troubleshooting?

**Comment by jcohlmeyer** [comment]
Did you install the dependencies with `php please:update`?

**Comment by codybuell** [comment]
I re-ran `php please update:addons`, still nothing displayed.

**Comment by jcohlmeyer** [comment]
1. Are you sure you selected the correct API & enabled it in the Google Developers Console? Namely `Google Analytics API` https://statamic.com/marketplace/addons/google-analytics/docs#reporting-setup

2. Did you try clearing caches `php please clear:cache`

3. Do you see any browser Ajax requests to the API endpoints (such as: `/cp/addons/google-analytics/ajax/top-browsers?startDate=&endDate=&url=` ? If so what is in the response for these requests?
A response to this endpoint should look something like this: ```{"labels":["Safari"],"points":[5],"colours":["#5AC8FA"]}```

3. Are you sure you have the correct View ID entered and the credentials file is named and saved in the correct location?

**Comment by codybuell** [comment]
Ugh, it was number 1.  The naming is very inconvenient on Google's end.  Searching for 'Google Analytics API' gets you "Google Analytics Reporting API" and "Analytics API".  I had only the former selected.  Might be worth updating the docs to just say "Analytics API" and specifically point out "not Google Analytics Reporting API".

Thanks for the help!

**Comment by krsilas** [comment]
I have a similar issue. Reporting works except for the page views data and the analytics field type. ``
Cannot read property 'page_views' of undefined at GoogleAnalyticsLineChart.makeChart (scripts.js? [sm]:210)
``
Ajax endpoints for _total-visitors-and-page-views_ and _most-visited-pages_ return valid responses tho.
I also ran `php please update:addons` and `php please clear:cache`. My system is running Statamic 2.11.14

**Comment by krsilas** [comment]
Ok, apparently the issue was that I was using a different locale, which isn't supported by the addon. The Vue Component tries to get the translation for 'Page Views' and 'Visitors' from the `Statamic.translations['addon.GoogleAnalytics::cp']` object which does not exist for unsupported languages. For every other String it falls back to the english one but not in this case. 
I don't understand the architecture enough to fix this other than providing a fallback for those to labels. I solved it by duplicating the 'en' folder in `/lang` and renaming it to my country code.

**Comment by jcohlmeyer** [comment]
@krsilas what local are you using? I just tried this out with the fr local and am not getting any errors. Also if you are still seeing this issue without duplicating the language folder could you please open up a new issue?

Thanks,
Jonathan

**Comment by krsilas** [comment]
@jcohlmeyer thanks, here is my issue: https://github.com/jrc9designstudio/statamic-google-analytics-v2/issues/15
