### ISSUE TITLE
Collections sort doesn't appear to be working correctly

### ISSUE THREAD

**Issue by cibgraphics** [jrc9designstudio/statamic-google-analytics-v2#6]
Sorting a collection based on Google Analytics hits doesn't appear to be functioning as expected.

```
{{ collection:blog as="posts" limit="3" sort="{ google_analytics:hits }" }}
```

This is the code that I am using. This brings this result: 

![screen shot 2018-12-12 at 3 54 57 pm](https://user-images.githubusercontent.com/972737/49904375-30296900-fe27-11e8-9e4c-32ef7f7eda5e.png)

As you can see the hits are not being sorted by highest to lowest. I also have another blog post that has more than the 2nd article just to confirm that it isn't sorting correctly.

Example with `limit-"4"`

![screen shot 2018-12-12 at 4 02 23 pm](https://user-images.githubusercontent.com/972737/49904456-6666e880-fe27-11e8-8637-ba6f69c3175e.png)

**Comment by jcohlmeyer** [comment]
Thanks for pointing out this issue @cibgraphics, this has now been fixed in the most recent version: https://github.com/jrc9designstudio/statamic-google-analytics-v2/releases/tag/2.2.4

**Comment by jcohlmeyer** [comment]
Please note the syntax for sorting by his has changed to: `{{ collection:blog filter="google_analytics" sort="none" }}`
