### ISSUE TITLE
IP Anonymization - Legal requirement in some countries

### ISSUE THREAD

**Issue by madsem** [jrc9designstudio/statamic-google-analytics-v2#7]
Hi,

just purchased your plugin, good job :)
But I'm missing the option to activate IP anonymization, which is a legal requirement in all EU countries by now.

https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization

Would it be possible to quickly add this to the tracking code?

**Comment by jcohlmeyer** [comment]
Yes, I can add this to the tracking code for the next release, thanks for the feedback.

**Comment by jcohlmeyer** [comment]
I have added the setting here if you can't wait for the next release: https://github.com/jrc9designstudio/statamic-google-analytics-v2/commit/2c5eabfa6d025b1e7be29bd4fa59f388bf0197e9

**Comment by madsem** [comment]
wow, that was fast. Thanks a lot :)

**Comment by jcohlmeyer** [comment]
Okay, this has been added for 2.3.0 https://github.com/jrc9designstudio/statamic-google-analytics-v2/releases/tag/2.3.0 thanks again for the feedback @madsem
