### ISSUE TITLE
Control panel instruction (unsuitable link)

### ISSUE THREAD

**Issue by jimblue** [jrc9designstudio/statamic-google-analytics-v2#9]
Hi,

In the instruction text of **Enable Enhanced Link Attribution**  option there is a link:

https://support.google.com/analytics/answer/2558867#enable

It's not giving propre information about the use case, maybe because the content have change. (it's a page about the Google Analytics chrome extension, which is deprecated since 2017)

Cheers

**Comment by jimblue** [comment]
awesome thanks for the new release! 🎉

**Comment by jcohlmeyer** [comment]
No problem, thanks for the feedback 😃
